In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/annan/Downloads/efficienza_tpl_filtered.csv")
df = df.reset_index(drop=False)
df

,level_0,level_1,level_2,level_3,level_4,level_5,Frequenza,Territorio,Dominio,Indicatore,...,"'Stato dell""'osservazione'",Territorio (NOTE_REF_AREA),Codifica territoriale ufficiale Istat,Indicatore (NOTE_DATA_TYPE),Descrizione indicatore,Fonte,Tempo (NOTE_TIME_PERIOD),Anno base,Unità di misura,Unità di moltiplicazione
0,Annuale,Piemonte,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2014,4537,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
1,Annuale,Piemonte,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2015,5084,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
2,Annuale,Piemonte,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2016,5042,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
3,Annuale,Piemonte,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2017,5197,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
4,Annuale,Piemonte,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2018,5026,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Annuale,Sardegna,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2019,3411,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
196,Annuale,Sardegna,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2020,2424,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
197,Annuale,Sardegna,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2021,3488,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
198,Annuale,Sardegna,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2022,3726,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN
199,Annuale,Sardegna,Qualità dei servizi,Posti-km offerti dal Tpl,Totale,2025,2023,3406,NaN,NaN,...,tram,filobus,metropolitana,funicolare o funivia (inclusi i servizi ettom...,"trasporti per vie d""'acqua.'",Istat: Indagine Dati ambientali nelle città,NaN,NaN,Valori per abitante,NaN

In [3]:
df = df.loc[:,["level_1", "Frequenza", "Territorio"]]
df.columns = ["Territorio", "Anno", "Osservazioni"]
df

    Territorio  Anno  Osservazioni
0     Piemonte  2014          4537
1     Piemonte  2015          5084
2     Piemonte  2016          5042
3     Piemonte  2017          5197
4     Piemonte  2018          5026
..         ...   ...           ...
195   Sardegna  2019          3411
196   Sardegna  2020          2424
197   Sardegna  2021          3488
198   Sardegna  2022          3726
199   Sardegna  2023          3406

[200 rows x 3 columns]

In [4]:
df2 = pd.read_csv("C:/Users/annan/Downloads/indice_cultura.csv")
df2

                                         Frequenza  \
Annuale Piemonte  Paesaggio e patrimonio culturale
        Piemonte  Paesaggio e patrimonio culturale
        Piemonte  Paesaggio e patrimonio culturale
        Piemonte  Paesaggio e patrimonio culturale
        Piemonte  Paesaggio e patrimonio culturale
...                                            ...
        Sardegna  Paesaggio e patrimonio culturale
        Sardegna  Paesaggio e patrimonio culturale
        Sardegna  Paesaggio e patrimonio culturale
        Sardegna  Paesaggio e patrimonio culturale
        Sardegna  Paesaggio e patrimonio culturale

                                                  Territorio Dominio  \
Annuale Piemonte  Densità e rilevanza del patrimonio museale  Totale
        Piemonte  Densità e rilevanza del patrimonio museale  Totale
        Piemonte  Densità e rilevanza del patrimonio museale  Totale
        Piemonte  Densità e rilevanza del patrimonio museale  Totale
        Piemonte  Densità e rilevanza del patrimonio museale  Totale
...                                                      ...     ...
        Sardegna  Densità e rilevanza del patrimonio museale  Totale
        Sardegna  Densità e rilevanza del patrimonio museale  Totale
        Sardegna  Densità e rilevanza del patrimonio museale  Totale
        Sardegna  Densità e rilevanza del patrimonio museale  Totale
        Sardegna  Densità e rilevanza del patrimonio museale  Totale

                  Indicatore  Sesso  Edizione  TIME_PERIOD  Osservazione  \
Annuale Piemonte        2025   2015      1.19          NaN           NaN
        Piemonte        2025   2018      1.17          NaN           NaN
        Piemonte        2025   2019      1.08          NaN           NaN
        Piemonte        2025   2020      1.05          NaN           NaN
        Piemonte        2025   2021      1.18          NaN           NaN
...                      ...    ...       ...          ...           ...
        Sardegna        2025   2018      0.35          NaN           NaN
        Sardegna        2025   2019      0.37          NaN           NaN
        Sardegna        2025   2020      0.31          NaN           NaN
        Sardegna        2025   2021      0.39          NaN           NaN
        Sardegna        2025   2022      0.32          NaN           NaN

                  'Stato dell"'osservazione'  Territorio (NOTE_REF_AREA)  \
Annuale Piemonte                         NaN                         NaN
        Piemonte                         NaN                         NaN
        Piemonte                         NaN                         NaN
        Piemonte                         NaN                         NaN
        Piemonte                         NaN                         NaN
...                                      ...                         ...
        Sardegna                         NaN                         NaN
        Sardegna                         NaN                         NaN
        Sardegna                         NaN                         NaN
        Sardegna                         NaN                         NaN
        Sardegna                         NaN                         NaN

                              Codifica territoriale ufficiale Istat  \
Annuale Piemonte  'Numero di strutture espositive permanenti per...
        Piemonte  'Numero di strutture espositive permanenti per...
        Piemonte  'Numero di strutture espositive permanenti per...
        Piemonte  'Numero di strutture espositive permanenti per...
        Piemonte  'Numero di strutture espositive permanenti per...
...                                                             ...
        Sardegna  'Numero di strutture espositive permanenti per...
        Sardegna  'Numero di strutture espositive permanenti per...
        Sardegna  'Numero di strutture espositive permanenti per...
        Sardegna  'Numero di strutture espositive permanenti per...
        Sardegna  'Numero di strutture espositive permanenti per...

                                        Indicatore (NOTE_DATA_TYPE)  \
Annuale Piemonte   aree archeologiche e monumenti aperti al pubb...
        Piemonte   aree archeologiche e monumenti aperti al pubb...
        Piemonte   aree archeologiche e monumenti aperti al pubb...
        Piemonte   aree archeologiche e monumenti aperti al pubb...
        Piemonte   aree archeologiche e monumenti aperti al pubb...
...                                                             ...
        Sardegna   aree archeologiche e monumenti aperti al pubb...
        Sardegna   aree archeologiche e monumenti aperti al pubb...
        Sardegna   aree archeologiche e monumenti aperti al pubb...
        Sardegna   aree archeologiche e monumenti aperti al pubb...
        Sardegna   aree archeologiche e monumenti aperti al pubb...

                                     Descrizione indicatore  \
Annuale Piemonte   ponderato per il numero dei visitatori.'
        Piemonte   ponderato per il numero dei visitatori.'
        Piemonte   ponderato per il numero dei visitatori.'
        Piemonte   ponderato per il numero dei visitatori.'
        Piemonte   ponderato per il numero dei visitatori.'
...                                                     ...
        Sardegna   ponderato per il numero dei visitatori.'
        Sardegna   ponderato per il numero dei visitatori.'
        Sardegna   ponderato per il numero dei visitatori.'
        Sardegna   ponderato per il numero dei visitatori.'
        Sardegna   ponderato per il numero dei visitatori.'

                                                              Fonte  \
Annuale Piemonte  Istat: Indagine sui musei e le istituzioni sim...
        Piemonte  Istat: Indagine sui musei e le istituzioni sim...
        Piemonte  Istat: Indagine sui musei e le istituzioni sim...
        Piemonte  Istat: Indagine sui musei e le istituzioni sim...
        Piemonte  Istat: Indagine sui musei e le istituzioni sim...
...                                                             ...
        Sardegna  Istat: Indagine sui musei e le istituzioni sim...
        Sardegna  Istat: Indagine sui musei e le istituzioni sim...
        Sardegna  Istat: Indagine sui musei e le istituzioni sim...
        Sardegna  Istat: Indagine sui musei e le istituzioni sim...
        Sardegna  Istat: Indagine sui musei e le istituzioni sim...

                  Tempo (NOTE_TIME_PERIOD)  Anno base Unità di misura  \
Annuale Piemonte                       NaN        NaN     Per 100 km2
        Piemonte                       NaN        NaN     Per 100 km2
        Piemonte                       NaN        NaN     Per 100 km2
        Piemonte                       NaN        NaN     Per 100 km2
        Piemonte                       NaN        NaN     Per 100 km2
...                                    ...        ...             ...
        Sardegna                       NaN        NaN     Per 100 km2
        Sardegna                       NaN        NaN     Per 100 km2
        Sardegna                       NaN        NaN     Per 100 km2
        Sardegna                       NaN        NaN     Per 100 km2
        Sardegna                       NaN        NaN     Per 100 km2

                  Unità di moltiplicazione
Annuale Piemonte                       NaN
        Piemonte                       NaN
        Piemonte                       NaN
        Piemonte                       NaN
        Piemonte                       NaN
...                                    ...
        Sardegna                       NaN
        Sardegna                       NaN
        Sardegna                       NaN
        Sardegna                       NaN
        Sardegna                       NaN

[120 rows x 18 columns]

In [5]:
df2 = df2.droplevel(0)

In [6]:
df2.head()

,Frequenza,Territorio,Dominio,Indicatore,Sesso,Edizione,TIME_PERIOD,Osservazione,"'Stato dell""'osservazione'",Territorio (NOTE_REF_AREA),Codifica territoriale ufficiale Istat,Indicatore (NOTE_DATA_TYPE),Descrizione indicatore,Fonte,Tempo (NOTE_TIME_PERIOD),Anno base,Unità di misura,Unità di moltiplicazione
Piemonte,Paesaggio e patrimonio culturale,Densità e rilevanza del patrimonio museale,Totale,2025,2015,1.19,NaN,NaN,NaN,NaN,'Numero di strutture espositive permanenti per...,aree archeologiche e monumenti aperti al pubb...,ponderato per il numero dei visitatori.',Istat: Indagine sui musei e le istituzioni sim...,NaN,NaN,Per 100 km2,NaN
Piemonte,Paesaggio e patrimonio culturale,Densità e rilevanza del patrimonio museale,Totale,2025,2018,1.17,NaN,NaN,NaN,NaN,'Numero di strutture espositive permanenti per...,aree archeologiche e monumenti aperti al pubb...,ponderato per il numero dei visitatori.',Istat: Indagine sui musei e le istituzioni sim...,NaN,NaN,Per 100 km2,NaN
Piemonte,Paesaggio e patrimonio culturale,Densità e rilevanza del patrimonio museale,Totale,2025,2019,1.08,NaN,NaN,NaN,NaN,'Numero di strutture espositive permanenti per...,aree archeologiche e monumenti aperti al pubb...,ponderato per il numero dei visitatori.',Istat: Indagine sui musei e le istituzioni sim...,NaN,NaN,Per 100 km2,NaN
Piemonte,Paesaggio e patrimonio culturale,Densità e rilevanza del patrimonio museale,Totale,2025,2020,1.05,NaN,NaN,NaN,NaN,'Numero di strutture espositive permanenti per...,aree archeologiche e monumenti aperti al pubb...,ponderato per il numero dei visitatori.',Istat: Indagine sui musei e le istituzioni sim...,NaN,NaN,Per 100 km2,NaN
Piemonte,Paesaggio e patrimonio culturale,Densità e rilevanza del patrimonio museale,Totale,2025,2021,1.18,NaN,NaN,NaN,NaN,'Numero di strutture espositive permanenti per...,aree archeologiche e monumenti aperti al pubb...,ponderato per il numero dei visitatori.',Istat: Indagine sui musei e le istituzioni sim...,NaN,NaN,Per 100 km2,NaN

In [7]:
#df2 = df.loc[:,["Sesso", "Edizione"]]
#df.columns = ["Territorio", "Anno", "Osservazioni"]
df2.columns

Index(['Frequenza', 'Territorio', 'Dominio', 'Indicatore', 'Sesso', 'Edizione',
       'TIME_PERIOD', 'Osservazione', ''Stato dell"'osservazione'',
       'Territorio (NOTE_REF_AREA)', 'Codifica territoriale ufficiale Istat',
       'Indicatore (NOTE_DATA_TYPE)', 'Descrizione indicatore', 'Fonte',
       'Tempo (NOTE_TIME_PERIOD)', 'Anno base', 'Unità di misura',
       'Unità di moltiplicazione'],
      dtype='object')